version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: population_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  get_data:
    build:
      context: .
      dockerfile: Dockerfile.get_data
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=postgresql+psycopg2://postgres:postgres@db:5432/population_db

  print_data:
    build:
      context: .
      dockerfile: Dockerfile.print_data
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=postgresql+psycopg2://postgres:postgres@db:5432/population_db

volumes:
  postgres_data: